"""initial tables

Revision ID: 14f1697de9dd
Revises: 
Create Date: 2026-08-26 08:16:45.141217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14f1697de9dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fng_value', sa.Integer(), nullable=True),
    sa.Column('fng_label', sa.Text(), nullable=True),
    sa.Column('coverage', sa.Text(), nullable=True),
    sa.Column('market_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_markets', sa.Text(), nullable=True),
    sa.Column('source_signals', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_captured_at', 'snapshot', ['captured_at'], unique=False)
    op.create_table('asset_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('change_24h', sa.Numeric(), nullable=True),
    sa.Column('high_24h', sa.Numeric(), nullable=True),
    sa.Column('low_24h', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('volume_24h', sa.Numeric(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('ath', sa.Numeric(), nullable=True),
    sa.Column('ath_change_pct', sa.Numeric(), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(), nullable=True),
    sa.Column('total_supply', sa.Numeric(), nullable=True),
    sa.Column('max_supply', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_snapshot_symbol_time', 'asset_snapshot', ['symbol', 'captured_at'], unique=False)
    op.create_index('idx_asset_snapshot_time', 'asset_snapshot', ['captured_at'], unique=False)
    op.create_table('trending_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trending_symbol_time', 'trending_snapshot', ['symbol', 'captured_at'], unique=False)
    op.create_index('idx_trending_time', 'trending_snapshot', ['captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trending_time', table_name='trending_snapshot')
    op.drop_index('idx_trending_symbol_time', table_name='trending_snapshot')
    op.drop_table('trending_snapshot')
    op.drop_index('idx_asset_snapshot_time', table_name='asset_snapshot')
    op.drop_index('idx_asset_snapshot_symbol_time', table_name='asset_snapshot')
    op.drop_table('asset_snapshot')
    op.drop_index('idx_snapshot_captured_at', table_name='snapshot')
    op.drop_table('snapshot')
    # ### end Alembic commands ###
