"""trending real columns

Revision ID: d5a9fdfbd2a0
Revises: 14f1697de9dd
Create Date: 2026-08-26 09:01:51.032524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a9fdfbd2a0'
down_revision: Union[str, Sequence[str], None] = '14f1697de9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trending_snapshot', sa.Column('coin_id', sa.Text(), nullable=True))
    op.add_column('trending_snapshot', sa.Column('price_usd', sa.Numeric(), nullable=True))
    op.add_column('trending_snapshot', sa.Column('price_change_24h_usd', sa.Numeric(), nullable=True))
    op.add_column('trending_snapshot', sa.Column('market_cap_usd', sa.Numeric(), nullable=True))
    op.add_column('trending_snapshot', sa.Column('total_volume_usd', sa.Numeric(), nullable=True))
    op.drop_column('trending_snapshot', 'price_change_24h')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trending_snapshot', sa.Column('price_change_24h', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('trending_snapshot', 'total_volume_usd')
    op.drop_column('trending_snapshot', 'market_cap_usd')
    op.drop_column('trending_snapshot', 'price_change_24h_usd')
    op.drop_column('trending_snapshot', 'price_usd')
    op.drop_column('trending_snapshot', 'coin_id')
    # ### end Alembic commands ###
