# utils/symbol_ids.py

COINGECKO_IDS: dict[str, str] = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "SOL": "solana",
    "XRP": "ripple",
    "ADA": "cardano",
    "BNB": "binancecoin",
    "DOGE": "dogecoin",
    "POL": "polygon-ecosystem-token",
    "AVAX": "avalanche-2",
    "DOT": "polkadot",
    "LINK": "chainlink",
    "UNI": "uniswap",
    "LTC": "litecoin",
    "USDT": "tether",
    "USDC": "usd-coin",
    "SHIB": "shiba-inu",
    "DAI": "dai",
    "BCH": "bitcoin-cash",
    "XLM": "stellar",
    "NEAR": "near",
    "VET": "vechain",
    "TRX": "tron",
    "ATOM": "cosmos",
    "SUI": "sui",
    "ARB": "arbitrum",
    "FTM": "fantom",
    "OP": "optimism",
    "GRAM": "the-open-network",
    "HYPE": "hyperliquid",
    "OKB": "okb",
    "PYUSD": "paypal-usd",
    "PI": "pi-network",
    "LEO": "leo-token",
    "XMR": "monero",
    "USDE": "ethena-usde",
    "CC": "canton-network",
    "WLFI": "world-liberty-financial",
    "HBAR": "hedera-hashgraph",
    "MNT": "mantle",
    "PAXG": "pax-gold",
    "PEPE": "pepe",
    "FLOKI": "floki",
    "AAVE": "aave",
    "MKR": "maker",
    "CRO": "crypto-com-chain",
    "TAO": "bittensor",
    "USDG": "global-dollar",
    "INJ": "injective-protocol",
    "SKY": "sky",
    "ICP": "internet-computer",
    "APT": "aptos",
    "ALGO": "algorand",
    "XTZ": "tezos",
    "EGLD": "elrond-erd-2",
    "FET": "fetch-ai",
    "RENDER": "render-token",
    "ETHFI": "ether-fi",
    "GRT": "the-graph",
    "JUP": "jupiter-exchange-solana",
    "PYTH": "pyth-network",
    "ZEC": "zcash",
    "USDS": "usds",
    "USD1": "usd1-wlfi",
    "QNT": "quant-network",
    "XAUT": "tether-gold",
    "M": "memecore",
    "DEXE": "dexe",
    "ASTER": "aster-2",
    "ONDO": "ondo-finance",
    "RLUSD": "ripple-usd",
    "USDD": "usdd",
    "WLD": "worldcoin-wld",
    "BGB": "bitget-token",
    "ETC": "ethereum-classic",
    "MORPHO": "morpho",
    "U": "united-stables",
    "KCS": "kucoin-shares",
    "BEAT": "audiera",
    "KAS": "kaspa",
    "STABLE": "stable-2",
    "FIGR_HELOC": "figure-heloc",
    "RAIN": "rain",
    "WBT": "whitebit",
    "AWETH": "aave-v3-weth",
    "JST": "just",
    "USDY": "ondo-us-dollar-yield",
    "LAB": "lab",
    "HTX": "htx-dao",
    "USDF": "falcon-finance",
    "BFUSD": "bfusd",
    "EUTBL": "eutbl",
    "BCAP": "blockchain-capital",
    "USDGO": "usdgo",
    "NEXO": "nexo",
    "ENA": "ethena",
    "ADI": "adi-token",
    "GT": "gatechain-token",
    "BUIDL": "blackrock-usd-institutional-digital-liquidity-fund",
    "NIGHT": "midnight-3",
    "BDX": "beldex",
    "USYC": "hashnote-usyc",
    "USD0": "usual-usd",
    "A7A5": "a7a5",
    "TUSD": "true-usd",
    "HASH": "hash-2",
    "USX": "usx",
    "PUMP": "pump-fun",
    "JAAA": "janus-henderson-anemoy-aaa-clo-fund",
    "GHO": "gho",
    "VVV": "venice-token",
    "YLDS": "ylds",
    "FIL": "filecoin",
    "EURSAFO": "spiko-amundi-overnight-swap-fund-eur",
    "币安人生": "bianrensheng",
    "XDC": "xdce-crowd-sale",
    "PENGU": "pudgy-penguins",
    "TRUMP": "official-trump",
    "ZAMA": "zama",
    "USTB": "superstate-short-duration-us-government-securities-fund-ustb",
    "JTRSY": "janus-henderson-anemoy-treasury-fund",
    "FLR": "flare-networks",
    "EURC": "euro-coin",
    "PANCAKE": "pancakeswap-token",
    "AERO": "aerodrome-finance",
    "DASH": "dash",
    "SEI": "sei-network",
    "VIRTUAL": "virtual-protocol",
    "SUN": "sun-token",
    "CRV": "curve-dao-token",
    "FDUSD": "first-digital-usd",
    "GNO": "gnosis",
    "LUNC": "terra-luna",
    "JTO": "jito-governance-token",
    "NFT": "apenft",
    "BONK": "bonk",
    "TIA": "celestia",
    "ZRO": "layerzero",
    "KAITO": "kaito",
    "LDO": "lido-dao",
    "SPX": "spx6900",
    "BTT": "bittorrent",
    "BSV": "bitcoin-cash-sv",
    "MON": "monad",
    "STX": "blockstack",
    "PENDLE": "pendle",
    "CFX": "conflux-token",
    "IMX": "immutable-x",
    "JASMY": "jasmycoin",
    "DCR": "decred",
    "XPL": "plasma",
}


def resolve_ids(symbols: list[str]) -> tuple[dict[str, str], list[str]]:
    """Mapea símbolos del portal a coingecko_ids.

    Devuelve:
      - resolved: { "BTC": "bitcoin", ... } solo de los que tienen id
      - missing:  ["XYZ", ...] los que no están en el dict (sin datos posibles)
    """
    resolved: dict[str, str] = {}
    missing: list[str] = []

    for raw in symbols:
        sym = (raw or "").strip().upper()
        if not sym:
            continue
        cg_id = COINGECKO_IDS.get(sym)
        if cg_id:
            resolved[sym] = cg_id
        else:
            missing.append(sym)

    return resolved, missing
