ALLOWED_SOCIAL_ASSETS = {
  "BTC", "ETH", "SOL", "XRP", "ADA", "BNB", "DOGE", "POL", "AVAX", "DOT",
  "LINK", "UNI","LTC","USDT","USDC","SHIB","DAI","BCH","XLM","NEAR",
  "VET","TRX","ATOM","SUI","ARB","FTM", "OP","HYPE","PYUSD","GRAM",
  "OKB","PI","LEO","XMR","USDE","CC","WLFI","HBAR","MNT","PAXG",
  "PEPE", "FLOKI", "AAVE", "MKR", "CRO", "TAO", "USDG", "INJ", "SKY", "ICP",
  "APT", "ALGO", "XTZ", "EGLD", "FET", "RENDER", "ETHFI", "GRT", "JUP", "PYTH",
  "ZEC", "USDS", "USD1", "QNT", "XAUT", "M", "DEXE", "ASTER", "ONDO", "RLUSD",
  "USDD", "WLD", "BGB", "ETC", "MORPHO", "U", "KCS", "BEAT", "KAS", "STABLE",
  "FIGR_HELOC", "RAIN", "WBT", "AWETH", "JST", "USDY", "LAB", "HTX", "USDF", "BFUSD",
  "EUTBL", "BCAP", "USDGO", "NEXO", "ENA", "ADI", "GT", "BUIDL", "NIGHT", "BDX",
  "USYC", "A7A5", "TUSD", "HASH", "USX", "USD0", "FIL", "YLDS", "VVV", "PENGU",
  "GHO", "JAAA", "PUMP", "USTB", "JTRSY", "EURSAFO", "ZAMA", "TRUMP", "XDC", "币安人生",
  "FLR", "EURC", "CAKE", "AERO", "DASH", "SEI", "VIRTUAL", "SUN", "CRV", "FDUSD",
  "SPX", "TIA", "ZRO", "KAITO", "LDO", "GNO", "LUNC", "JTO", "NFT", "BONK",
  "BTT", "BSV", "MON", "STX", "PENDLE", "CFX", "IMX", "JASMY", "DCR", "XPL",
  "BTW", "LIT", "USDTB", "KAU", "OUSG", "APXUSD", "KITE", "FF", "SOFID", "UB",
  "PIEVERSE", "OHM", "ONYC", "CRVUSD", "SAFE", "MARSCOIN", "AI", "KAG", "REUSD", "GRASS",
  "CASHCAT", "AUSD", "USDAI", "RAY", "KOGE", "PONS", "SYRUP", "CVX", "CARDS", "FRAX",
  "TWT", "KAIA", "2Z", "IOTA", "ULTIMA", "AKE", "COMP", "STRK", "USAT", "SKR",
  "USELESS", "APYUSD", "BORG", "TEL", "COCO", "AXS", "RUNE", "MX", "DRV", "牛来",
  "MCAT", "APEPE", "ENS", "TIBBIR", "PC0000031", "GRX", "BR", "STONK", "EURCV", "SAFO",
  "EIGEN", "THETA", "WIF", "B", "NPC", "H", "ZBCN", "PRL", "AR", "BTSE",
  "ANTFUN", "GENIUS", "XCN", "KMNO", "龙虾", "ZCAT", "AKT", "CHZ", "NEO", "SHFL",
  "GUSD", "XEC", "TRAC", "SNX", "BC", "DGAI", "SFP", "BP", "ZEN", "RAIL",
  "APE", "JPYSC", "A", "CASH", "MET", "AVUSD", "RLB", "OZO", "AWE", "VSN",
  "SHRUB", "CP", "FIRO", "LAPTOP", "LSK", "EMBER", "INDEX", "UP", "HNT", "ZANO",
  "RAM", "BTR", "EDGE", "TAKE", "PEAQ", "CHIP", "ANSEM", "VELVET", "ZYLO", "EDEL",
  "SOPH", "POWER", "IOST", "WMTX", "NOCK", "M87", "FOGO", "ILV", "AURORA", "ARC",
  "ASTRO", "RSFIRO", "ZORA", "ONG", "VTHO", "CVC", "REZ", "BFC", "G", "SCRT",
  "FONE", "BLUECHIP", "DEBIT", "ORCA", "S", "ORBIO", "AIX", "CPOOL", "BICO", "WELL",
  "KII", "CORE", "NIL", "PROM", "UAI", "SYN", "ZZZ", "FWA", "PAIR", "STORJ",
  "PLUME", "ZETA", "LUNA", "MANTRA", "TRUE", "FARTCOIN", "MINA", "STRCX", "AIOZ", "SENT",
  "JPYC", "BAT", "META", "SN51", "DBR", "GEOD", "SAND", "ATH", "Q", "KNTQ",
  "RSR", "QTUM", "DYDX", "FORM", "SOSO", "SUPER", "FLUID", "NXM", "ZK", "ONE",
  "COTI", "CNPY", "BNKR", "FLOCK", "ORE", "ARK", "AVA", "ZKC", "NEON", "GLM",
}

FALLBACK_ASSETS = ["BTC", "ETH", "USDT", "BNB", "USDC", "XRP", "SOL", "TRX", "FIGR_HELOC", "ZEC"]

NARRATIVE_TAGS = {
    "majors-led",
    "layer1",
    "meme",
    "defi",
    "selective breadth",
    "mixed participation",
    "trend expansion",
    "risk-off",
}